connect_timeout=2
network_timeout=30
base_path=/fastdfs_data_and_log
load_fdfs_parameters_from_tracker=false
storage_sync_file_max_delay=86400
url_have_group_name=true
tracker_server=127.0.0.1:22122
storage_server_port=23000
group_name=group1
store_path_count=1
store_path0=/fastdfs_data_and_log/storage
log_level=info
log_filename=
response_mode=proxy
anti_steal_token=false
token_check_fail_buff_size=256
token_check_fail_content_type=text/html
flv_support=true
flv_extension=flv
group_count=0
http.mime_types_filename=/etc/fdfs/mime.types
http.default_content_type=application/octet-stream
