disabled=false
bind_addr=
port=22122
connect_timeout=30
network_timeout=60
base_path=/fastdfs_data_and_log/tracker
max_connections=256
accept_threads=1
work_threads=4
store_lookup=2
store_server=0
store_path=0
download_server=0
reserved_storage_space=10%
log_level=info
run_by_group=
run_by_user=
allow_hosts=*
sync_log_buff_interval=10
check_active_interval=120
thread_stack_size=64KB
storage_ip_changed_auto_adjust=true
storage_sync_file_max_delay=86400
storage_sync_file_max_time=300
use_trunk_file=false
